//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPPromoWeb_equipo_12A
{


    public partial class Paso3
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new TPPromoWeb_equipo_12A.Master Master
        {
            get
            {
                return ((TPPromoWeb_equipo_12A.Master)(base.Master));
            }
        }
    }
}
